# Generated by Django 4.1.4 on 2023-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20201211_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderstatus",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Ready", "Ready")],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
